title:        ScriptEditor Blog
description:  activate
url:          https://ds0x.github.io          # root URL of the site
baseurl:      /scripteditor.app               # repository name
theme:        null                            # no default theme
markdown:     kramdown
kramdown:
  input: GFM
