title:      tell application “Script Editor” to activate
description: "AppleScript can't be contained."
author:     ds
baseurl:    ""            # ← leave empty for user sites
url:        "https://ds0x.github.io/scripteditor.app"   # ← update for project sites

theme:      null          # we’ll use our own CSS
markdown:   kramdown
kramdown:
  input: GFM
